export { default as TourApi } from './tourApi';
export { default as PromotionApi } from './promotionApi';
export { default as AuthApi } from './authApi';
export { default as CustomerApi } from './customerApi';
export { default as ScheduleApi } from './scheduleApi';
export { default as BookingApi } from './bookingApi';
export { default as CheckoutApi } from './checkoutApi';
export { default as AdminApi } from './adminApi';
export { default as NewsApi } from './newsApi';