server:
  port: 8080
  servlet:
    context-path: /api/v1
    session:
      tracking-modes: cookie
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      file-size-threshold: 1KB

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/toursaoviet
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

jwt:
  signerKey: "q7Tw92RvdkeKfQJl+7mhtwfnQJuJRoseRNLfA3rrPlE+sKvBao2hyhGCu46opa4Q"

momo:
  partnerCode: "MOMOBKUN20180529"
  accessKey: "klm05TvNBzhg7h7j"
  secretKey: "at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa"
  url: "https://a19a-113-23-44-70.ngrok-free.app"

app:
  name: SaoViet
  description: Dự án Spring Boot quản lý website Tour Sao Việt
  version: 1.0.0