export const ROUTERS = {
    USER: {
        HOME: "",
        LOGINPAGE: "auth/login",
        REGISTERPAGE: "auth/register",
        PROFILE: "users/infor",
        PASSWORD: "users/password",
        NEWS: "news/index",
        NEWSDETAIL: "news/detail",
        HOTELS: "hotels/index",
        HOTELSDETAIL: "hotels/detail",
        TOURS: "tours/index",
        TOURCATEGORY: "tours/category",
        TOURLIST: "tours/category/:id",
        TOURSDETAIL: "tours/detail/:id",
        GUIDES: "guides/index",
        GUIDESDETAIL: "guides/detail/:id",
        GUIDESLIST: "guides/list/:id",
        ORDERS: "orders/:id",
        ORDERSMESSAGE: "orders/message",
        CALENDARS: "/calendars/index",
        SEARCH: "/tours/search",
    },
    ADMIN: {
        HOME: "/manage",
        LOGINPAGE: "/manage/auth/login",
        CUSTOMERSPAGE: "/manage/customers/index",
        TOURSPAGE: "/manage/tours/index",
        TOURINSERTPAGE: "/manage/tours/create",
        TOURUPDATEPAGE: "/manage/tours/edit/:id",
        GUIDESPAGE: "/manage/guides/index",
        GUIDEINSERTPAGE: "/manage/guides/create",
        GUIDEUPDATEPAGE: "/manage/guides/edit/:id",
        ASSIGNMENTSPAGE: "/manage/assignments/index",
        CALENDARSPAGE: "/manage/calendars/index",
        CALENDARDETAILSPAGE: "/manage/calendars/detail/:id",
        PROFILEPAGE: "/manage/infor",
        PASSWORDPAGE: "/manage/password",
        DASHBOARDPAGE: "/manage/dashboards/index",
    },
    ERROR: {
        ERROR500: 'error/500',
        MANAGEERROR500: 'manage/error/500',
    },
}