export const ROUTERS = {
    USER: {
        HOME: "",
        LOGINPAGE: "auth/login",
        REGISTERPAGE: "auth/register",
        PROFILE: "customer/infor",
        PASSWORD: "customer/password",
        NEWS: "news/index",
        NEWSDETAIL: "news/detail",
        TOUR: "tour/index",
        TOURCATEGORY: "tour/category",
        TOURLIST: "tour/category/:id",
        TOURDETAIL: "tour/detail/:id",
        BOOKING: "booking/:id",
        BOOKINGMESSAGE: "booking/message",
        CALENDAR: "/calendar/index",
        CALENDARDETAIL: "/calendar/detail/:id",
        SEARCH: "/tour/search",
        SEARCHDESTINATION: "/tour/search-destination",
        ACTIVATE: "/customer/activate/:id",
        ABOUT: "/about",
        DESTINATIONS: "/destinations/index",
    },
    ADMIN: {
        HOME: "/manage",
        LOGINPAGE: "/manage/auth/login",
        CUSTOMERPAGE: "/manage/customer/index",
        TOURPAGE: "/manage/tour/index",
        TOURINSERTPAGE: "/manage/tour/create",
        TOURUPDATEPAGE: "/manage/tour/edit/:id",
        GUIDESPAGE: "/manage/guides/index",
        GUIDEINSERTPAGE: "/manage/guides/create",
        GUIDEUPDATEPAGE: "/manage/guides/edit/:id",
        ASSIGNMENTSPAGE: "/manage/assignments/index",
        CALENDARPAGE: "/manage/calendar/index",
        CALENDARDETAILSPAGE: "/manage/calendar/detail/:id",
        PROFILEPAGE: "/manage/infor",
        PASSWORDPAGE: "/manage/password",
        DASHBOARDPAGE: "/manage/dashboard/index",
    },
    ERROR: {
        ERROR500: 'error/500',
        MANAGEERROR500: 'manage/error/500',
    },
}